# Generated by Django 5.0.3 on 2024-09-03 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cus_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cus_ph',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_name',
            field=models.CharField(default='Default Event', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_place',
            field=models.CharField(default='Default Place', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_persons',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
