# Generated by Django 5.0.3 on 2024-09-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_rename_booking_date_booking_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='event',
            name='img',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='default name', max_length=100),
        ),
    ]
