# Generated by Django 5.0.3 on 2024-09-05 08:30

import eventapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_remove_event_email_remove_event_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_place',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=eventapp.models.get_default_image, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=255),
        ),
    ]
