# Generated by Django 5.0.3 on 2024-09-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_customusermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
