# Generated by Django 5.0.3 on 2024-09-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='satisfaction_level',
            field=models.CharField(choices=[('poor', 'Poor'), ('average', 'Average'), ('good', 'Good'), ('very_good', 'Very Good'), ('excellent', 'Excellent')], default='average', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
